# Generated by Django 4.0.4 on 2022-08-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoanCurrentDaysDelinquent', models.FloatField(default=0)),
                ('LP_CustomerPrincipalPayments', models.FloatField(default=0)),
                ('LP_GrossPrincipalLoss', models.FloatField(default=0)),
                ('LP_CustomerPayments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('LP_InterestandFees', models.FloatField(default=0)),
                ('LP_ServiceFees', models.FloatField(default=0)),
                ('MonthlyLoanPayment', models.FloatField(default=0)),
                ('AvailableBankcardCredit', models.FloatField(default=0)),
                ('RevolvingCreditBalance', models.FloatField(default=0)),
            ],
        ),
    ]
