# Generated by Django 4.1 on 2022-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanDefaultPredictorNB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='AvailableBankcardCredit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='LP_CustomerPayments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='features',
            name='LP_CustomerPrincipalPayments',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='LP_GrossPrincipalLoss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='LP_InterestandFees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='LP_ServiceFees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='LoanCurrentDaysDelinquent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='features',
            name='MonthlyLoanPayment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='features',
            name='RevolvingCreditBalance',
            field=models.FloatField(default=0),
        ),
    ]
